// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.yuandian.data.common;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PUserInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PUserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PErrorInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PErrorInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PChatInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PChatInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PChatInfos_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PChatInfos_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\"6\n\tPUserInfo\022\013\n\003uid\030\001 \001(\005" +
      "\022\014\n\004name\030\002 \001(\t\022\016\n\006openid\030\003 \001(\t\"\'\n\nPError" +
      "Info\022\013\n\003cmd\030\001 \001(\003\022\014\n\004code\030\002 \001(\003\"v\n\tPChat" +
      "Info\022\013\n\003uid\030\001 \001(\003\022\021\n\ttargetUid\030\002 \001(\003\022\013\n\003" +
      "mid\030\003 \001(\003\022\014\n\004type\030\004 \001(\005\022\017\n\007context\030\005 \001(\t" +
      "\022\016\n\006isRead\030\006 \001(\003\022\r\n\005cTime\030\007 \001(\003\"*\n\nPChat" +
      "Infos\022\034\n\010chatInfo\030\001 \002(\0132\n.PChatInfoB\034\n\030c" +
      "om.yuandian.data.commonP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PUserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PUserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PUserInfo_descriptor,
        new java.lang.String[] { "Uid", "Name", "Openid", });
    internal_static_PErrorInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PErrorInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PErrorInfo_descriptor,
        new java.lang.String[] { "Cmd", "Code", });
    internal_static_PChatInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PChatInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PChatInfo_descriptor,
        new java.lang.String[] { "Uid", "TargetUid", "Mid", "Type", "Context", "IsRead", "CTime", });
    internal_static_PChatInfos_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PChatInfos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PChatInfos_descriptor,
        new java.lang.String[] { "ChatInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
