// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.yuandian.data.common;

/**
 * Protobuf type {@code PChatInfos}
 */
public final class PChatInfos extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PChatInfos)
    PChatInfosOrBuilder {
  // Use PChatInfos.newBuilder() to construct.
  private PChatInfos(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PChatInfos(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final PChatInfos defaultInstance;
  public static PChatInfos getDefaultInstance() {
    return defaultInstance;
  }

  public PChatInfos getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private PChatInfos(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.yuandian.data.common.PChatInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = chatInfo_.toBuilder();
            }
            chatInfo_ = input.readMessage(com.yuandian.data.common.PChatInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(chatInfo_);
              chatInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yuandian.data.common.Common.internal_static_PChatInfos_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yuandian.data.common.Common.internal_static_PChatInfos_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yuandian.data.common.PChatInfos.class, com.yuandian.data.common.PChatInfos.Builder.class);
  }

  public static com.google.protobuf.Parser<PChatInfos> PARSER =
      new com.google.protobuf.AbstractParser<PChatInfos>() {
    public PChatInfos parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PChatInfos(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<PChatInfos> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int CHATINFO_FIELD_NUMBER = 1;
  private com.yuandian.data.common.PChatInfo chatInfo_;
  /**
   * <code>required .PChatInfo chatInfo = 1;</code>
   */
  public boolean hasChatInfo() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .PChatInfo chatInfo = 1;</code>
   */
  public com.yuandian.data.common.PChatInfo getChatInfo() {
    return chatInfo_;
  }
  /**
   * <code>required .PChatInfo chatInfo = 1;</code>
   */
  public com.yuandian.data.common.PChatInfoOrBuilder getChatInfoOrBuilder() {
    return chatInfo_;
  }

  private void initFields() {
    chatInfo_ = com.yuandian.data.common.PChatInfo.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasChatInfo()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, chatInfo_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, chatInfo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.yuandian.data.common.PChatInfos parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuandian.data.common.PChatInfos parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuandian.data.common.PChatInfos parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuandian.data.common.PChatInfos parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuandian.data.common.PChatInfos parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yuandian.data.common.PChatInfos parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.yuandian.data.common.PChatInfos parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.yuandian.data.common.PChatInfos parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.yuandian.data.common.PChatInfos parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yuandian.data.common.PChatInfos parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.yuandian.data.common.PChatInfos prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PChatInfos}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PChatInfos)
      com.yuandian.data.common.PChatInfosOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuandian.data.common.Common.internal_static_PChatInfos_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuandian.data.common.Common.internal_static_PChatInfos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuandian.data.common.PChatInfos.class, com.yuandian.data.common.PChatInfos.Builder.class);
    }

    // Construct using com.yuandian.data.common.PChatInfos.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getChatInfoFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (chatInfoBuilder_ == null) {
        chatInfo_ = com.yuandian.data.common.PChatInfo.getDefaultInstance();
      } else {
        chatInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yuandian.data.common.Common.internal_static_PChatInfos_descriptor;
    }

    public com.yuandian.data.common.PChatInfos getDefaultInstanceForType() {
      return com.yuandian.data.common.PChatInfos.getDefaultInstance();
    }

    public com.yuandian.data.common.PChatInfos build() {
      com.yuandian.data.common.PChatInfos result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.yuandian.data.common.PChatInfos buildPartial() {
      com.yuandian.data.common.PChatInfos result = new com.yuandian.data.common.PChatInfos(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (chatInfoBuilder_ == null) {
        result.chatInfo_ = chatInfo_;
      } else {
        result.chatInfo_ = chatInfoBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yuandian.data.common.PChatInfos) {
        return mergeFrom((com.yuandian.data.common.PChatInfos)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yuandian.data.common.PChatInfos other) {
      if (other == com.yuandian.data.common.PChatInfos.getDefaultInstance()) return this;
      if (other.hasChatInfo()) {
        mergeChatInfo(other.getChatInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasChatInfo()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yuandian.data.common.PChatInfos parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yuandian.data.common.PChatInfos) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.yuandian.data.common.PChatInfo chatInfo_ = com.yuandian.data.common.PChatInfo.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.yuandian.data.common.PChatInfo, com.yuandian.data.common.PChatInfo.Builder, com.yuandian.data.common.PChatInfoOrBuilder> chatInfoBuilder_;
    /**
     * <code>required .PChatInfo chatInfo = 1;</code>
     */
    public boolean hasChatInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .PChatInfo chatInfo = 1;</code>
     */
    public com.yuandian.data.common.PChatInfo getChatInfo() {
      if (chatInfoBuilder_ == null) {
        return chatInfo_;
      } else {
        return chatInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>required .PChatInfo chatInfo = 1;</code>
     */
    public Builder setChatInfo(com.yuandian.data.common.PChatInfo value) {
      if (chatInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chatInfo_ = value;
        onChanged();
      } else {
        chatInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .PChatInfo chatInfo = 1;</code>
     */
    public Builder setChatInfo(
        com.yuandian.data.common.PChatInfo.Builder builderForValue) {
      if (chatInfoBuilder_ == null) {
        chatInfo_ = builderForValue.build();
        onChanged();
      } else {
        chatInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .PChatInfo chatInfo = 1;</code>
     */
    public Builder mergeChatInfo(com.yuandian.data.common.PChatInfo value) {
      if (chatInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            chatInfo_ != com.yuandian.data.common.PChatInfo.getDefaultInstance()) {
          chatInfo_ =
            com.yuandian.data.common.PChatInfo.newBuilder(chatInfo_).mergeFrom(value).buildPartial();
        } else {
          chatInfo_ = value;
        }
        onChanged();
      } else {
        chatInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .PChatInfo chatInfo = 1;</code>
     */
    public Builder clearChatInfo() {
      if (chatInfoBuilder_ == null) {
        chatInfo_ = com.yuandian.data.common.PChatInfo.getDefaultInstance();
        onChanged();
      } else {
        chatInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .PChatInfo chatInfo = 1;</code>
     */
    public com.yuandian.data.common.PChatInfo.Builder getChatInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getChatInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>required .PChatInfo chatInfo = 1;</code>
     */
    public com.yuandian.data.common.PChatInfoOrBuilder getChatInfoOrBuilder() {
      if (chatInfoBuilder_ != null) {
        return chatInfoBuilder_.getMessageOrBuilder();
      } else {
        return chatInfo_;
      }
    }
    /**
     * <code>required .PChatInfo chatInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.yuandian.data.common.PChatInfo, com.yuandian.data.common.PChatInfo.Builder, com.yuandian.data.common.PChatInfoOrBuilder> 
        getChatInfoFieldBuilder() {
      if (chatInfoBuilder_ == null) {
        chatInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.yuandian.data.common.PChatInfo, com.yuandian.data.common.PChatInfo.Builder, com.yuandian.data.common.PChatInfoOrBuilder>(
                getChatInfo(),
                getParentForChildren(),
                isClean());
        chatInfo_ = null;
      }
      return chatInfoBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:PChatInfos)
  }

  static {
    defaultInstance = new PChatInfos(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:PChatInfos)
}

