// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.yuandian.data.common;

public interface PChatInfosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PChatInfos)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .PChatInfo chatInfo = 1;</code>
   */
  boolean hasChatInfo();
  /**
   * <code>required .PChatInfo chatInfo = 1;</code>
   */
  com.yuandian.data.common.PChatInfo getChatInfo();
  /**
   * <code>required .PChatInfo chatInfo = 1;</code>
   */
  com.yuandian.data.common.PChatInfoOrBuilder getChatInfoOrBuilder();
}
