// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.yuandian.data.common;

public interface PChatInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PChatInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 uid = 1;</code>
   */
  boolean hasUid();
  /**
   * <code>optional int64 uid = 1;</code>
   */
  long getUid();

  /**
   * <code>optional int64 targetUid = 2;</code>
   */
  boolean hasTargetUid();
  /**
   * <code>optional int64 targetUid = 2;</code>
   */
  long getTargetUid();

  /**
   * <code>optional int64 mid = 3;</code>
   */
  boolean hasMid();
  /**
   * <code>optional int64 mid = 3;</code>
   */
  long getMid();

  /**
   * <code>optional int32 type = 4;</code>
   *
   * <pre>
   *1文字，2表情，3图片，。。。。后面再添加
   * </pre>
   */
  boolean hasType();
  /**
   * <code>optional int32 type = 4;</code>
   *
   * <pre>
   *1文字，2表情，3图片，。。。。后面再添加
   * </pre>
   */
  int getType();

  /**
   * <code>optional string context = 5;</code>
   */
  boolean hasContext();
  /**
   * <code>optional string context = 5;</code>
   */
  java.lang.String getContext();
  /**
   * <code>optional string context = 5;</code>
   */
  com.google.protobuf.ByteString
      getContextBytes();

  /**
   * <code>optional int64 isRead = 6;</code>
   */
  boolean hasIsRead();
  /**
   * <code>optional int64 isRead = 6;</code>
   */
  long getIsRead();

  /**
   * <code>optional int64 cTime = 7;</code>
   */
  boolean hasCTime();
  /**
   * <code>optional int64 cTime = 7;</code>
   */
  long getCTime();
}
