// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.yuandian.data.common;

/**
 * Protobuf type {@code PChatInfo}
 *
 * <pre>
 * 聊天消息体
 * </pre>
 */
public final class PChatInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PChatInfo)
    PChatInfoOrBuilder {
  // Use PChatInfo.newBuilder() to construct.
  private PChatInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PChatInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final PChatInfo defaultInstance;
  public static PChatInfo getDefaultInstance() {
    return defaultInstance;
  }

  public PChatInfo getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private PChatInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            uid_ = input.readInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            targetUid_ = input.readInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            mid_ = input.readInt64();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            type_ = input.readInt32();
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            context_ = bs;
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            isRead_ = input.readInt64();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            cTime_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yuandian.data.common.Common.internal_static_PChatInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yuandian.data.common.Common.internal_static_PChatInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yuandian.data.common.PChatInfo.class, com.yuandian.data.common.PChatInfo.Builder.class);
  }

  public static com.google.protobuf.Parser<PChatInfo> PARSER =
      new com.google.protobuf.AbstractParser<PChatInfo>() {
    public PChatInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PChatInfo(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<PChatInfo> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int UID_FIELD_NUMBER = 1;
  private long uid_;
  /**
   * <code>optional int64 uid = 1;</code>
   */
  public boolean hasUid() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int64 uid = 1;</code>
   */
  public long getUid() {
    return uid_;
  }

  public static final int TARGETUID_FIELD_NUMBER = 2;
  private long targetUid_;
  /**
   * <code>optional int64 targetUid = 2;</code>
   */
  public boolean hasTargetUid() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int64 targetUid = 2;</code>
   */
  public long getTargetUid() {
    return targetUid_;
  }

  public static final int MID_FIELD_NUMBER = 3;
  private long mid_;
  /**
   * <code>optional int64 mid = 3;</code>
   */
  public boolean hasMid() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int64 mid = 3;</code>
   */
  public long getMid() {
    return mid_;
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private int type_;
  /**
   * <code>optional int32 type = 4;</code>
   *
   * <pre>
   *1文字，2表情，3图片，。。。。后面再添加
   * </pre>
   */
  public boolean hasType() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int32 type = 4;</code>
   *
   * <pre>
   *1文字，2表情，3图片，。。。。后面再添加
   * </pre>
   */
  public int getType() {
    return type_;
  }

  public static final int CONTEXT_FIELD_NUMBER = 5;
  private java.lang.Object context_;
  /**
   * <code>optional string context = 5;</code>
   */
  public boolean hasContext() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string context = 5;</code>
   */
  public java.lang.String getContext() {
    java.lang.Object ref = context_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        context_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string context = 5;</code>
   */
  public com.google.protobuf.ByteString
      getContextBytes() {
    java.lang.Object ref = context_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      context_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISREAD_FIELD_NUMBER = 6;
  private long isRead_;
  /**
   * <code>optional int64 isRead = 6;</code>
   */
  public boolean hasIsRead() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional int64 isRead = 6;</code>
   */
  public long getIsRead() {
    return isRead_;
  }

  public static final int CTIME_FIELD_NUMBER = 7;
  private long cTime_;
  /**
   * <code>optional int64 cTime = 7;</code>
   */
  public boolean hasCTime() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional int64 cTime = 7;</code>
   */
  public long getCTime() {
    return cTime_;
  }

  private void initFields() {
    uid_ = 0L;
    targetUid_ = 0L;
    mid_ = 0L;
    type_ = 0;
    context_ = "";
    isRead_ = 0L;
    cTime_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, uid_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(2, targetUid_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt64(3, mid_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, type_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getContextBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeInt64(6, isRead_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeInt64(7, cTime_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, uid_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, targetUid_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, mid_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, type_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getContextBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, isRead_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, cTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.yuandian.data.common.PChatInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuandian.data.common.PChatInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuandian.data.common.PChatInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuandian.data.common.PChatInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuandian.data.common.PChatInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yuandian.data.common.PChatInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.yuandian.data.common.PChatInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.yuandian.data.common.PChatInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.yuandian.data.common.PChatInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yuandian.data.common.PChatInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.yuandian.data.common.PChatInfo prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PChatInfo}
   *
   * <pre>
   * 聊天消息体
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PChatInfo)
      com.yuandian.data.common.PChatInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuandian.data.common.Common.internal_static_PChatInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuandian.data.common.Common.internal_static_PChatInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuandian.data.common.PChatInfo.class, com.yuandian.data.common.PChatInfo.Builder.class);
    }

    // Construct using com.yuandian.data.common.PChatInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      uid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      targetUid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      mid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      type_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      context_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      isRead_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000020);
      cTime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yuandian.data.common.Common.internal_static_PChatInfo_descriptor;
    }

    public com.yuandian.data.common.PChatInfo getDefaultInstanceForType() {
      return com.yuandian.data.common.PChatInfo.getDefaultInstance();
    }

    public com.yuandian.data.common.PChatInfo build() {
      com.yuandian.data.common.PChatInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.yuandian.data.common.PChatInfo buildPartial() {
      com.yuandian.data.common.PChatInfo result = new com.yuandian.data.common.PChatInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.uid_ = uid_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.targetUid_ = targetUid_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.mid_ = mid_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.context_ = context_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.isRead_ = isRead_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.cTime_ = cTime_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yuandian.data.common.PChatInfo) {
        return mergeFrom((com.yuandian.data.common.PChatInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yuandian.data.common.PChatInfo other) {
      if (other == com.yuandian.data.common.PChatInfo.getDefaultInstance()) return this;
      if (other.hasUid()) {
        setUid(other.getUid());
      }
      if (other.hasTargetUid()) {
        setTargetUid(other.getTargetUid());
      }
      if (other.hasMid()) {
        setMid(other.getMid());
      }
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasContext()) {
        bitField0_ |= 0x00000010;
        context_ = other.context_;
        onChanged();
      }
      if (other.hasIsRead()) {
        setIsRead(other.getIsRead());
      }
      if (other.hasCTime()) {
        setCTime(other.getCTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yuandian.data.common.PChatInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yuandian.data.common.PChatInfo) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long uid_ ;
    /**
     * <code>optional int64 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }
    /**
     * <code>optional int64 uid = 1;</code>
     */
    public Builder setUid(long value) {
      bitField0_ |= 0x00000001;
      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 uid = 1;</code>
     */
    public Builder clearUid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      uid_ = 0L;
      onChanged();
      return this;
    }

    private long targetUid_ ;
    /**
     * <code>optional int64 targetUid = 2;</code>
     */
    public boolean hasTargetUid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 targetUid = 2;</code>
     */
    public long getTargetUid() {
      return targetUid_;
    }
    /**
     * <code>optional int64 targetUid = 2;</code>
     */
    public Builder setTargetUid(long value) {
      bitField0_ |= 0x00000002;
      targetUid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 targetUid = 2;</code>
     */
    public Builder clearTargetUid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      targetUid_ = 0L;
      onChanged();
      return this;
    }

    private long mid_ ;
    /**
     * <code>optional int64 mid = 3;</code>
     */
    public boolean hasMid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 mid = 3;</code>
     */
    public long getMid() {
      return mid_;
    }
    /**
     * <code>optional int64 mid = 3;</code>
     */
    public Builder setMid(long value) {
      bitField0_ |= 0x00000004;
      mid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 mid = 3;</code>
     */
    public Builder clearMid() {
      bitField0_ = (bitField0_ & ~0x00000004);
      mid_ = 0L;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <code>optional int32 type = 4;</code>
     *
     * <pre>
     *1文字，2表情，3图片，。。。。后面再添加
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 type = 4;</code>
     *
     * <pre>
     *1文字，2表情，3图片，。。。。后面再添加
     * </pre>
     */
    public int getType() {
      return type_;
    }
    /**
     * <code>optional int32 type = 4;</code>
     *
     * <pre>
     *1文字，2表情，3图片，。。。。后面再添加
     * </pre>
     */
    public Builder setType(int value) {
      bitField0_ |= 0x00000008;
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 type = 4;</code>
     *
     * <pre>
     *1文字，2表情，3图片，。。。。后面再添加
     * </pre>
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object context_ = "";
    /**
     * <code>optional string context = 5;</code>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string context = 5;</code>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          context_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string context = 5;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string context = 5;</code>
     */
    public Builder setContext(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      context_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string context = 5;</code>
     */
    public Builder clearContext() {
      bitField0_ = (bitField0_ & ~0x00000010);
      context_ = getDefaultInstance().getContext();
      onChanged();
      return this;
    }
    /**
     * <code>optional string context = 5;</code>
     */
    public Builder setContextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      context_ = value;
      onChanged();
      return this;
    }

    private long isRead_ ;
    /**
     * <code>optional int64 isRead = 6;</code>
     */
    public boolean hasIsRead() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 isRead = 6;</code>
     */
    public long getIsRead() {
      return isRead_;
    }
    /**
     * <code>optional int64 isRead = 6;</code>
     */
    public Builder setIsRead(long value) {
      bitField0_ |= 0x00000020;
      isRead_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 isRead = 6;</code>
     */
    public Builder clearIsRead() {
      bitField0_ = (bitField0_ & ~0x00000020);
      isRead_ = 0L;
      onChanged();
      return this;
    }

    private long cTime_ ;
    /**
     * <code>optional int64 cTime = 7;</code>
     */
    public boolean hasCTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 cTime = 7;</code>
     */
    public long getCTime() {
      return cTime_;
    }
    /**
     * <code>optional int64 cTime = 7;</code>
     */
    public Builder setCTime(long value) {
      bitField0_ |= 0x00000040;
      cTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 cTime = 7;</code>
     */
    public Builder clearCTime() {
      bitField0_ = (bitField0_ & ~0x00000040);
      cTime_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PChatInfo)
  }

  static {
    defaultInstance = new PChatInfo(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:PChatInfo)
}

