// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.yuandian.data.common;

public interface PErrorInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PErrorInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 cmd = 1;</code>
   */
  boolean hasCmd();
  /**
   * <code>optional int64 cmd = 1;</code>
   */
  long getCmd();

  /**
   * <code>optional int64 code = 2;</code>
   */
  boolean hasCode();
  /**
   * <code>optional int64 code = 2;</code>
   */
  long getCode();
}
