// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.yuandian.data.common;

public interface PUserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PUserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 uid = 1;</code>
   */
  boolean hasUid();
  /**
   * <code>optional int32 uid = 1;</code>
   */
  int getUid();

  /**
   * <code>optional string name = 2;</code>
   */
  boolean hasName();
  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string openid = 3;</code>
   */
  boolean hasOpenid();
  /**
   * <code>optional string openid = 3;</code>
   */
  java.lang.String getOpenid();
  /**
   * <code>optional string openid = 3;</code>
   */
  com.google.protobuf.ByteString
      getOpenidBytes();
}
