// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_agr.proto

package com.yuandian.data.rpc;

public interface RItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 sdId = 1;</code>
   */
  boolean hasSdId();
  /**
   * <code>optional int32 sdId = 1;</code>
   */
  int getSdId();
}
