// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.yuandian.data.message;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PAuth_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PAuth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PSendChat_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PSendChat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PGetChatRecord_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PGetChatRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\032\014common.proto\"5\n\005PAuth\022\013" +
      "\n\003uid\030\001 \001(\003\022\020\n\010deviceId\030\002 \001(\t\022\r\n\005token\030\003" +
      " \001(\t\"%\n\tPSendChat\022\030\n\004chat\030\001 \001(\0132\n.PChatI" +
      "nfo\"1\n\016PGetChatRecord\022\020\n\010targetId\030\001 \001(\003\022" +
      "\r\n\005limit\030\002 \001(\003B\035\n\031com.yuandian.data.mess" +
      "ageP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yuandian.data.common.Common.getDescriptor(),
        }, assigner);
    internal_static_PAuth_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PAuth_descriptor,
        new java.lang.String[] { "Uid", "DeviceId", "Token", });
    internal_static_PSendChat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PSendChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PSendChat_descriptor,
        new java.lang.String[] { "Chat", });
    internal_static_PGetChatRecord_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PGetChatRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PGetChatRecord_descriptor,
        new java.lang.String[] { "TargetId", "Limit", });
    com.yuandian.data.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
