// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.yuandian.data.message;

public interface PAuthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PAuth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 uid = 1;</code>
   */
  boolean hasUid();
  /**
   * <code>optional int64 uid = 1;</code>
   */
  long getUid();

  /**
   * <code>optional string deviceId = 2;</code>
   */
  boolean hasDeviceId();
  /**
   * <code>optional string deviceId = 2;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>optional string deviceId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>optional string token = 3;</code>
   */
  boolean hasToken();
  /**
   * <code>optional string token = 3;</code>
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 3;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
