// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.yuandian.data.message;

/**
 * Protobuf type {@code PGetChatRecord}
 *
 * <pre>
 *cmd=1005  return 获取聊天记录
 * </pre>
 */
public final class PGetChatRecord extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PGetChatRecord)
    PGetChatRecordOrBuilder {
  // Use PGetChatRecord.newBuilder() to construct.
  private PGetChatRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PGetChatRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final PGetChatRecord defaultInstance;
  public static PGetChatRecord getDefaultInstance() {
    return defaultInstance;
  }

  public PGetChatRecord getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private PGetChatRecord(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            targetId_ = input.readInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            limit_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yuandian.data.message.Message.internal_static_PGetChatRecord_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yuandian.data.message.Message.internal_static_PGetChatRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yuandian.data.message.PGetChatRecord.class, com.yuandian.data.message.PGetChatRecord.Builder.class);
  }

  public static com.google.protobuf.Parser<PGetChatRecord> PARSER =
      new com.google.protobuf.AbstractParser<PGetChatRecord>() {
    public PGetChatRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PGetChatRecord(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<PGetChatRecord> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int TARGETID_FIELD_NUMBER = 1;
  private long targetId_;
  /**
   * <code>optional int64 targetId = 1;</code>
   */
  public boolean hasTargetId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int64 targetId = 1;</code>
   */
  public long getTargetId() {
    return targetId_;
  }

  public static final int LIMIT_FIELD_NUMBER = 2;
  private long limit_;
  /**
   * <code>optional int64 limit = 2;</code>
   */
  public boolean hasLimit() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int64 limit = 2;</code>
   */
  public long getLimit() {
    return limit_;
  }

  private void initFields() {
    targetId_ = 0L;
    limit_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, targetId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(2, limit_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, targetId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, limit_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.yuandian.data.message.PGetChatRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuandian.data.message.PGetChatRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuandian.data.message.PGetChatRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuandian.data.message.PGetChatRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuandian.data.message.PGetChatRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yuandian.data.message.PGetChatRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.yuandian.data.message.PGetChatRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.yuandian.data.message.PGetChatRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.yuandian.data.message.PGetChatRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yuandian.data.message.PGetChatRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.yuandian.data.message.PGetChatRecord prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PGetChatRecord}
   *
   * <pre>
   *cmd=1005  return 获取聊天记录
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PGetChatRecord)
      com.yuandian.data.message.PGetChatRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuandian.data.message.Message.internal_static_PGetChatRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuandian.data.message.Message.internal_static_PGetChatRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuandian.data.message.PGetChatRecord.class, com.yuandian.data.message.PGetChatRecord.Builder.class);
    }

    // Construct using com.yuandian.data.message.PGetChatRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      targetId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      limit_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yuandian.data.message.Message.internal_static_PGetChatRecord_descriptor;
    }

    public com.yuandian.data.message.PGetChatRecord getDefaultInstanceForType() {
      return com.yuandian.data.message.PGetChatRecord.getDefaultInstance();
    }

    public com.yuandian.data.message.PGetChatRecord build() {
      com.yuandian.data.message.PGetChatRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.yuandian.data.message.PGetChatRecord buildPartial() {
      com.yuandian.data.message.PGetChatRecord result = new com.yuandian.data.message.PGetChatRecord(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.targetId_ = targetId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.limit_ = limit_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yuandian.data.message.PGetChatRecord) {
        return mergeFrom((com.yuandian.data.message.PGetChatRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yuandian.data.message.PGetChatRecord other) {
      if (other == com.yuandian.data.message.PGetChatRecord.getDefaultInstance()) return this;
      if (other.hasTargetId()) {
        setTargetId(other.getTargetId());
      }
      if (other.hasLimit()) {
        setLimit(other.getLimit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yuandian.data.message.PGetChatRecord parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yuandian.data.message.PGetChatRecord) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long targetId_ ;
    /**
     * <code>optional int64 targetId = 1;</code>
     */
    public boolean hasTargetId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 targetId = 1;</code>
     */
    public long getTargetId() {
      return targetId_;
    }
    /**
     * <code>optional int64 targetId = 1;</code>
     */
    public Builder setTargetId(long value) {
      bitField0_ |= 0x00000001;
      targetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 targetId = 1;</code>
     */
    public Builder clearTargetId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      targetId_ = 0L;
      onChanged();
      return this;
    }

    private long limit_ ;
    /**
     * <code>optional int64 limit = 2;</code>
     */
    public boolean hasLimit() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 limit = 2;</code>
     */
    public long getLimit() {
      return limit_;
    }
    /**
     * <code>optional int64 limit = 2;</code>
     */
    public Builder setLimit(long value) {
      bitField0_ |= 0x00000002;
      limit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 limit = 2;</code>
     */
    public Builder clearLimit() {
      bitField0_ = (bitField0_ & ~0x00000002);
      limit_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PGetChatRecord)
  }

  static {
    defaultInstance = new PGetChatRecord(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:PGetChatRecord)
}

