// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.yuandian.data.message;

public interface PGetChatRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PGetChatRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 targetId = 1;</code>
   */
  boolean hasTargetId();
  /**
   * <code>optional int64 targetId = 1;</code>
   */
  long getTargetId();

  /**
   * <code>optional int64 limit = 2;</code>
   */
  boolean hasLimit();
  /**
   * <code>optional int64 limit = 2;</code>
   */
  long getLimit();
}
