// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.yuandian.data.message;

/**
 * Protobuf type {@code PSendChat}
 *
 * <pre>
 *cmd=1004 return PChatInfo
 * </pre>
 */
public final class PSendChat extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PSendChat)
    PSendChatOrBuilder {
  // Use PSendChat.newBuilder() to construct.
  private PSendChat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PSendChat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final PSendChat defaultInstance;
  public static PSendChat getDefaultInstance() {
    return defaultInstance;
  }

  public PSendChat getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private PSendChat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.yuandian.data.common.PChatInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = chat_.toBuilder();
            }
            chat_ = input.readMessage(com.yuandian.data.common.PChatInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(chat_);
              chat_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yuandian.data.message.Message.internal_static_PSendChat_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yuandian.data.message.Message.internal_static_PSendChat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yuandian.data.message.PSendChat.class, com.yuandian.data.message.PSendChat.Builder.class);
  }

  public static com.google.protobuf.Parser<PSendChat> PARSER =
      new com.google.protobuf.AbstractParser<PSendChat>() {
    public PSendChat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PSendChat(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<PSendChat> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int CHAT_FIELD_NUMBER = 1;
  private com.yuandian.data.common.PChatInfo chat_;
  /**
   * <code>optional .PChatInfo chat = 1;</code>
   */
  public boolean hasChat() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .PChatInfo chat = 1;</code>
   */
  public com.yuandian.data.common.PChatInfo getChat() {
    return chat_;
  }
  /**
   * <code>optional .PChatInfo chat = 1;</code>
   */
  public com.yuandian.data.common.PChatInfoOrBuilder getChatOrBuilder() {
    return chat_;
  }

  private void initFields() {
    chat_ = com.yuandian.data.common.PChatInfo.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, chat_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, chat_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.yuandian.data.message.PSendChat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuandian.data.message.PSendChat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuandian.data.message.PSendChat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuandian.data.message.PSendChat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuandian.data.message.PSendChat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yuandian.data.message.PSendChat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.yuandian.data.message.PSendChat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.yuandian.data.message.PSendChat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.yuandian.data.message.PSendChat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yuandian.data.message.PSendChat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.yuandian.data.message.PSendChat prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PSendChat}
   *
   * <pre>
   *cmd=1004 return PChatInfo
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PSendChat)
      com.yuandian.data.message.PSendChatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuandian.data.message.Message.internal_static_PSendChat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuandian.data.message.Message.internal_static_PSendChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuandian.data.message.PSendChat.class, com.yuandian.data.message.PSendChat.Builder.class);
    }

    // Construct using com.yuandian.data.message.PSendChat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getChatFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (chatBuilder_ == null) {
        chat_ = com.yuandian.data.common.PChatInfo.getDefaultInstance();
      } else {
        chatBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yuandian.data.message.Message.internal_static_PSendChat_descriptor;
    }

    public com.yuandian.data.message.PSendChat getDefaultInstanceForType() {
      return com.yuandian.data.message.PSendChat.getDefaultInstance();
    }

    public com.yuandian.data.message.PSendChat build() {
      com.yuandian.data.message.PSendChat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.yuandian.data.message.PSendChat buildPartial() {
      com.yuandian.data.message.PSendChat result = new com.yuandian.data.message.PSendChat(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (chatBuilder_ == null) {
        result.chat_ = chat_;
      } else {
        result.chat_ = chatBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yuandian.data.message.PSendChat) {
        return mergeFrom((com.yuandian.data.message.PSendChat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yuandian.data.message.PSendChat other) {
      if (other == com.yuandian.data.message.PSendChat.getDefaultInstance()) return this;
      if (other.hasChat()) {
        mergeChat(other.getChat());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yuandian.data.message.PSendChat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yuandian.data.message.PSendChat) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.yuandian.data.common.PChatInfo chat_ = com.yuandian.data.common.PChatInfo.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.yuandian.data.common.PChatInfo, com.yuandian.data.common.PChatInfo.Builder, com.yuandian.data.common.PChatInfoOrBuilder> chatBuilder_;
    /**
     * <code>optional .PChatInfo chat = 1;</code>
     */
    public boolean hasChat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .PChatInfo chat = 1;</code>
     */
    public com.yuandian.data.common.PChatInfo getChat() {
      if (chatBuilder_ == null) {
        return chat_;
      } else {
        return chatBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .PChatInfo chat = 1;</code>
     */
    public Builder setChat(com.yuandian.data.common.PChatInfo value) {
      if (chatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chat_ = value;
        onChanged();
      } else {
        chatBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .PChatInfo chat = 1;</code>
     */
    public Builder setChat(
        com.yuandian.data.common.PChatInfo.Builder builderForValue) {
      if (chatBuilder_ == null) {
        chat_ = builderForValue.build();
        onChanged();
      } else {
        chatBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .PChatInfo chat = 1;</code>
     */
    public Builder mergeChat(com.yuandian.data.common.PChatInfo value) {
      if (chatBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            chat_ != com.yuandian.data.common.PChatInfo.getDefaultInstance()) {
          chat_ =
            com.yuandian.data.common.PChatInfo.newBuilder(chat_).mergeFrom(value).buildPartial();
        } else {
          chat_ = value;
        }
        onChanged();
      } else {
        chatBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .PChatInfo chat = 1;</code>
     */
    public Builder clearChat() {
      if (chatBuilder_ == null) {
        chat_ = com.yuandian.data.common.PChatInfo.getDefaultInstance();
        onChanged();
      } else {
        chatBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .PChatInfo chat = 1;</code>
     */
    public com.yuandian.data.common.PChatInfo.Builder getChatBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getChatFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .PChatInfo chat = 1;</code>
     */
    public com.yuandian.data.common.PChatInfoOrBuilder getChatOrBuilder() {
      if (chatBuilder_ != null) {
        return chatBuilder_.getMessageOrBuilder();
      } else {
        return chat_;
      }
    }
    /**
     * <code>optional .PChatInfo chat = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.yuandian.data.common.PChatInfo, com.yuandian.data.common.PChatInfo.Builder, com.yuandian.data.common.PChatInfoOrBuilder> 
        getChatFieldBuilder() {
      if (chatBuilder_ == null) {
        chatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.yuandian.data.common.PChatInfo, com.yuandian.data.common.PChatInfo.Builder, com.yuandian.data.common.PChatInfoOrBuilder>(
                getChat(),
                getParentForChildren(),
                isClean());
        chat_ = null;
      }
      return chatBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:PSendChat)
  }

  static {
    defaultInstance = new PSendChat(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:PSendChat)
}

