// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.yuandian.data.message;

public interface PSendChatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PSendChat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .PChatInfo chat = 1;</code>
   */
  boolean hasChat();
  /**
   * <code>optional .PChatInfo chat = 1;</code>
   */
  com.yuandian.data.common.PChatInfo getChat();
  /**
   * <code>optional .PChatInfo chat = 1;</code>
   */
  com.yuandian.data.common.PChatInfoOrBuilder getChatOrBuilder();
}
