// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push_message.proto

package com.yuandian.data.push;

public interface PushChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PushChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .PChatInfo chatInfo = 1;</code>
   */
  boolean hasChatInfo();
  /**
   * <code>optional .PChatInfo chatInfo = 1;</code>
   */
  com.yuandian.data.common.PChatInfo getChatInfo();
  /**
   * <code>optional .PChatInfo chatInfo = 1;</code>
   */
  com.yuandian.data.common.PChatInfoOrBuilder getChatInfoOrBuilder();
}
