// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push_message.proto

package com.yuandian.data.push;

public final class PushMessage {
  private PushMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushChatMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PushChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022push_message.proto\032\014common.proto\"/\n\017Pu" +
      "shChatMessage\022\034\n\010chatInfo\030\001 \001(\0132\n.PChatI" +
      "nfoB\032\n\026com.yuandian.data.pushP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yuandian.data.common.Common.getDescriptor(),
        }, assigner);
    internal_static_PushChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PushChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PushChatMessage_descriptor,
        new java.lang.String[] { "ChatInfo", });
    com.yuandian.data.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
